# Generated by Django 4.0.6 on 2022-07-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField(max_length=14)),
                ('tipo', models.CharField(max_length=100)),
                ('porcentagem', models.BooleanField(default=False)),
            ],
        ),
    ]
